# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Paula Chocron
tagline:          'Personal Webpage'
description:      'Email: pcho..@iiia.csic.es'
baseurl:          /index
url:              https://paulachocron.github.io


author:
  name:           'Paula Chocron'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/paulachocron
  
# Gems
gems: [jekyll-paginate]
