# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Paula Chocron
tagline:          ''
description:      'Email: pcho..@iiia.csic.es'
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/paulachocron
  
# Gems
gems: [jekyll-paginate]
